### ISSUE TITLE
Fix or delete Graph Front end test_rte

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNakerGraphFrontEnd#58]
I have done as much as I can to get these running.

https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/tree/gfe_integration_tests/gfe_integration_tests/test_rte

To build these you may need:
https://github.com/SpiNNakerManchester/SupportScripts/blob/gfe_integration_tests/automatic_make.sh

**Comment by rowleya** [comment]
I believe that these now work - I have updated the files so that they are actually tests.  The tests are:
 - test_rte_during_run_forever.py
 - test_rte_during_run.py
 - test_rte_start.py
 - test_run_too_long.py

The binaries need to be compiled as you suggest - not sure what this means for integration testing...

Note: There has been a change in SpiNNFrontEndCommon which has been made using the same gfe_integration_tests branch name.
