### ISSUE TITLE
SWERR when booting the machine for the first time

### ISSUE THREAD

**Issue by gmtuca** [SpiNNakerManchester/SpiNNakerGraphFrontEnd#9]
This problem was introduced when pulling commits from the work_flow_manager branch

**Comment by gmtuca** [comment]
Apologies. This should have been raised against the spiDB branch.

**Comment by gmtuca** [comment]
@alan-stokes @rowleya The issue we saw yesterday

**Comment by alan-stokes** [comment]
should be fixed in the mapping_work_flow branch. The issue was a missing depednancy between exeuctable binary fucntion requriing application data to be loaded first, becuase that was not explicitly defined, it was dependand on the position in the lsit to which function was ran first. In Spynnaker the order was different to gfe.

**Comment by alan-stokes** [comment]
was discovered to be a mismatch between laoding execuabltes and loading app data. Was fixed during auot_pause_and_resume so that loading executables requires loaded app data to be ran. worked and therefore this issue is now closed.
